### ISSUE TITLE
Build errors on Windows w/go 1.15 and 1.16

### ISSUE THREAD

**Issue by kfsone** [gonutz/prototype#10]
```
> go build .
go: finding module for package github.com/gonutz/prototype/draw
go: found github.com/gonutz/prototype/draw in github.com/gonutz/prototype v0.0.0-20210219081453-295a54f2a887
go: finding module for package github.com/gonutz/d3d9
go: finding module for package github.com/gonutz/mixer
go: finding module for package github.com/gonutz/w32
go: finding module for package github.com/gonutz/mixer/wav
go: found github.com/gonutz/d3d9 in github.com/gonutz/d3d9 v1.0.1
go: found github.com/gonutz/mixer in github.com/gonutz/mixer v0.0.0-20171129091500-a40121441cc5
go: found github.com/gonutz/mixer/wav in github.com/gonutz/mixer v0.0.0-20171129091500-a40121441cc5
go: found github.com/gonutz/w32 in github.com/gonutz/w32 v1.0.0
go: finding module for package github.com/gonutz/ds
go: found github.com/gonutz/ds in github.com/gonutz/ds v0.0.0-20170706082326-82969548412b
# github.com/gonutz/prototype/draw
..\..\..\..\..\pkg\mod\github.com\gonutz\prototype@v0.0.0-20210219081453-295a54f2a887\draw\window_windows.go:93:8: undefined: w32.UnregisterClassAtom
..\..\..\..\..\pkg\mod\github.com\gonutz\prototype@v0.0.0-20210219081453-295a54f2a887\draw\window_windows.go:442:7: undefined: w32.WM_MOUSEHWHEEL
..\..\..\..\..\pkg\mod\github.com\gonutz\prototype@v0.0.0-20210219081453-295a54f2a887\draw\window_windows.go:515:10: cannot use style & ^w32.WS_OVERLAPPEDWINDOW (type int32) as type uint32 in argument to w32.SetWindowLong
```

What version of go is wanted/desired? It might be worth adding a go.mod file (`go mod init`) so you can specify the go and dependency versions inline?

Steps to reproduce:

I tested with the built-in Windows Sandbox feature (if not enabled, hit start, type enough of 'turn windows features on' to get a completion, and enable 'Windows Sandbox' in the list of optional features). Could also be done with a virtual machine.

- Install latest git: https://github.com/git-for-windows/git/releases/download/v2.30.1.windows.1/Git-2.30.1-64-bit.exe
- Install go 1.16: https://golang.org/dl/go1.16.windows-amd64.msi
- Open a Powershell session (I'm a linux/bash guy, powershell is based on the same spec as bash so it's a little more natural to me)
-- hit start
-- type 'powershell'
- ensure git and go are installed (note: powershell supports completion on flags and arguments)
    >  gcm git -ea stop    # short for: get-command git -erroraction stop
    >  gcm go -ea stop
- create a local go project:
    >  cd (mkdir -f (join-path $env:GOPATH local/scratch))
- initialize local go module
    > go mod init local/scratch
- create a simple test file
    > notepad main.go
with the following code
    package main

    import "github.com/gonutz/prototype/draw"

    func main() {
        draw.RunWindow("Test", 640, 480, update)
    }

    func update(window draw.Window) {
        window.DrawLine(100, 100, 440, 380, draw.Blue)
    }
- install dependencies
    > go mod tidy
- attempt to run
    PS C:\Users\WDAGUtilityAccount\go\local\scratch> go run .
    \# github.com/gonutz/prototype/draw
    ..\..\pkg\mod\github.com\gonutz\prototype@v0.0.0-20210219081453-295a54f2a887\draw\window_windows.go:93:8: undefined: w32.UnregisterClassAtom
    ..\..\pkg\mod\github.com\gonutz\prototype@v0.0.0-20210219081453-295a54f2a887\draw\window_windows.go:442:7: undefined: w32.WM_MOUSEHWHEEL
    ..\..\pkg\mod\github.com\gonutz\prototype@v0.0.0-20210219081453-295a54f2a887\draw\window_windows.go:515:10: cannot use style & ^w32.WS_OVERLAPPEDWINDOW (type int32) as type uint32 in argument to w32.SetWindowLong

**Comment by gonutz** [comment]
You need to manually tell Go to use the latest version of the w32 library. It will use tag 1.0.0 by default which is very old. I know this because I just got [this comment](https://github.com/gonutz/w32/commit/ef4882556e3b2969c0b54b709ff69b09d8fc2857#commitcomment-47473811) on another repository :-)

Modules, yes, a subject I have been staying away from for as long as I could. I did not think it would be a problem for people. My way of working so far was that I keep all my repositories up to date and `go get -u` has done its job for me.

Now that modules are enabled by default I am afraid it is time for me to add module support to all my repositories. Please excuse me for not being all over this new feature. While I know from experience that reproducible builds from multiple repos is a problem, I think the module solution is very complex and I do not like the `v2` in the import path thing.

I have long bookmarked [this Go blog article](https://blog.golang.org/using-go-modules) about how to use modules but it is a five part, 10000 word article. I have read [the Go spec](https://golang.org/ref/spec) and it is now 27000 words. Is modules a third of the complexity of the whole programming language?

Anyway, rant mode off, I will, in the not-too-distant future, read up on modules, get used to them and add module support for my active repositories. Probably some vendor folders will fall prey to this update process.

P.S.: rant mode on again, I also hate the new [pkg.go.dev](https://pkg.go.dev/) website for online docs! It will not show some of my repos where I forgot a license file. Thus I only get an error and if I add a license it will not know about it. On godoc.org I had an "update this repo" link which would just get the latest changes. For pkg.go.dev I have to trigger some server or proxy or whatever and ARE YOU KIDDING ME?! Rant mode off for good now.

**Comment by kfsone** [comment]
Hey, I'm relatively new to golang itself, didn't mean to wave anybody's flag re modules. There seems to be a bare-minimum entry-level option for them where you can "go mod init; go mod tidy" and be done which captures the state of dependencies you built with. After that you wade into deeper waters but presumably mostly for corporate dev environments.

I have mentally side-lined modules as "like python requirements.txt".

But then, I've read the blog article 2x and understood it 0x, and I'm not even sure I know what the v2 thing is (I thought that was some fancy semantic-versioning thing). I was really just alluding to the basic go.mod file and I have no horses in the race :)

**Comment by kfsone** [comment]
(Closed because you provided the info necessary to build :)

**Comment by gonutz** [comment]
Alright but now you've triggered me, I am already up to my knees in modules and have already encountered some problems. It seems this feature really IS as complex as I thought. I have always liked how easy Go makes everything, but this is annoying. Still, I am on my way to make all of my repositories module-proof so it is a good thing you got me started on it. Thanks for the feedback! :-)

**Comment by kfsone** [comment]
If you blog about that adventure, I hope you'll drop a link here?

Most of my initial headaches seemed to anchor around stuff getting cached. `go clean -modcache` became my friend while I was learning. Also, `go mod edit -replace` is my frenemy. It seems to pay to be sparing: I tried making packages with sub-modules and Thaer Bae Googlers Sayething "At Scale". In each case, I ended up going with just one top-level go.mod file and it seemed to work beautifully.

I have to give most of the credit to GoLand, tho :) (I'm usually a vim/vs/vsc type person, but GoLand far exceeds the threshold of critically-useful functionality I set for using an additional tool)

**Comment by gonutz** [comment]
No blogging for now, I just moved a bunch of my repos over. My w32 and wui libraries now have a v2 folder which I quite honestly do not like very much. I followed [rsc's advice](https://blog.golang.org/v2-go-modules) and copied all the .go files over to a new sub-folder `v2` in the repo. This kind of messes up git version history (copied files have no history) and makes browsing github messy (it shows a lot more on the front page than when you go into a sub-folder and the URL contains a `/blob/master/`.

That is the `v2` thing I was talking about and now all import paths had to be changed to include the trailing `/v2`. Anyhow, I hope this pays off some time in the future. Reproducible builds are a pain that I now from work. I appreciate it that the Go authors put in effort to help with the problem. It is just that this solution has some draw backs.

**Comment by kfsone** [comment]
From the command line, you can find copies in history with -C, but a thought: maybe you can move the files and copy them back, since you'll be working on the copied versions. Anyway, please accept my _humble_ apologies and gratitude for tackling this.
