### ISSUE TITLE
Resize window with window.Resize() ?

### ISSUE THREAD

**Issue by nicolasdscp** [gonutz/prototype#14]
There is any way to resize the window via window.Resize() or anything else ?

**Comment by gonutz** [comment]
You have `draw.Window.SetFullscreen(bool)` to toggle fullscreen but a resizeable window is currently not possible. What is your use-case?

**Comment by nicolasdscp** [comment]
I currently use a `glfw` window and, here is actually the state of the function `draw.Window.SetFullscreen(bool)`

```go
func (w *window) SetFullscreen(f bool) {
	// TODO Find out how to toggle full screen in GLFW 3.1 and tell OpenGL about
	// it.
}
```

Does the following function could be implemented ?

```go
// Set the size of the window, work only with glfw/sdl windows.
func (w *window) SetSize(width, height int) {
	w.window.SetSize(width, height)
}
```

**Comment by gonutz** [comment]
Oh you are right, I forgot about that TODO there. Anyway, would it be OK to just implement fullscreen in GLFW, maybe by switching to GLFW 3.3? Or do you really need full control over the size at runtime? Or do you want to have a flag that makes the window resizeable by the user?

**Comment by nicolasdscp** [comment]
Eventually I would like to be able to resize the window during the execution or, that the window can be resized by the user. A flag to set the window resizeable by the user could be great !

**Comment by gonutz** [comment]
May I ask what you are working on? I have found that for my use-cases I did not really need a resizeable window. It was part of this library at some point but then I made it simpler on myself to implement this library by taking out that functionality. What I found was that I really do not need it. I have not really missed it once I added fullscreen and fixed window modes. Toggling between those was enough for my games.

**Comment by gonutz** [comment]
I just fixed the fullscreen for GLFW. Still, if you really need a resizeable window I would be interested in your concrete use-case.

**Comment by nicolasdscp** [comment]
For some time I have been looking for lightweight abstractions of OpenGL. Personally, I was trying to make a component library in the same style as Qt or Gtk. And although your library is a game engine, it provided a good abstraction and good performance. So I was planning to use your library to make desktop applications and not necessarily games. That's why the ability to resize the window was relevant. I was specifically looking for something similar to [P5js](https://p5js.org/)

**Comment by gonutz** [comment]
You mean a GUI library? That is a nice idea, I have actually used this library at work for a Linux desktop app with multiple tab-pages, each with some buttons, text and number edits. I was thinking about adding a sample to create GUIs. Immediate mode GUIs are a thing these days and I would love to see you create a good-looking thing with this (quite basic) library of mine :-)

How about you start on your library and I start thinking about how to support resizeable windows on all the backends.

One question is the API, I would rather not make it a flag to `RunWindow` because then you are forced to set it always or pass a `0` or some constant when almost all of the time you will pass the same thing. I like the straight forward `RunWindow` function as it is.

Maybe a `Window.SetSize(int, int)` and a `Window.SetResizable(bool)` similary to `Window.SetFullscreen(bool)`. I find this was a nice way to add that functionality. Also you can change it per frame. The main idea here is that everything is done inside the update function so that no setup or teardown is required when using the `draw` library.

**Comment by nicolasdscp** [comment]
This is a very good idea however after some research I discovered [Gio](https://gioui.org/) and It's really related to that i looking for. I will definitely try to get a feel for this library first. I will contact you if I reconsider your proposal.

**Comment by gonutz** [comment]
Alright, I will close this issue then. Feel free to re-open it or open a new one if you like :-)
