### ISSUE TITLE
Web Assembly?

### ISSUE THREAD

**Issue by eboatwright** [gonutz/prototype#21]
Will there be any support for Web Assembly? I want to use this for game jams, but usually people don't want to download games, so I usually put web builds of my games. :smile:

**Comment by gonutz** [comment]
I know, that is something I have been noticing :-)

Actually I have never had a problem with ratings in [my Ludum Dare games](https://ldjam.com/users/gonutz/games) with putting a Windows and Linux build up, but I noticed in myself that just clicking a game and it starts running is really a nice and convenient way to experience it.

That is why I have created a game in JavaScript for the last LD.

I have thought about making a transpiler for my library, one way or another, to HTML and JS. I had no experience in web dev, though, so I first created that LD game. Then I created something for work and I am slowly starting to get used to web dev. I find it very easy, it was actually a joy to build things as a single-page JS fullscreen app. Now I am experimenting with HTML and the DOM. It turns out all of this is really easy to use and pretty friction-less, compared to writing cross platform desktop applications. I get now why people use it a lot ;-)

The thing is, I think I would rather use JS directly instead of writing a Go program that gets half-way converted. Because you can never convert everything automatically 100%. I like having control over everything that I do and having Go and a transpiler as a dependency when I really only want to create a single page JS game is quite a bit of overhead.

Also if I create a web game, everybody can play it. There is really no reason to include desktop games along with it for a game jam. Everybody will play the online version. So I just make sure that one runs fine and the problem is solved. Either I use Go and create desktop applications OR I use JS and only create a web game.

These are the reasons I decided against a web assembly, or whatever, transpiler thing for this library. Too much work for really no gain.

By the way, I am in the process of creating a video tutorial for this library. Since you create pixel art, I wanted to ask if you had a character run cycle animation to spare. I could use that in my video and of course would link to your profile so maybe we can get some more people to play your games. Until now I did not even have a pixel art example in my video script. But since it is an issue for you, I would add an example of DrawImageFilePart to show how to do pixel art with `prototype`. That would be cool!

**Comment by eboatwright** [comment]
Yeah I made a game engine for javascript called blueberryjs, and it's really good (in my _very_ humble opinion :laughing:) but, Ebiten works really good with web. :smile: I would LOVE to make a run cycle for your example! So, were you just thinking a 16x16 character? :smile:

**Comment by eboatwright** [comment]
I whipped out one of my old characters, and gave it a new coat of paint. So here's the character! It's just a run cycle, and the player is 16x16 pixels. :smile: https://drive.google.com/file/d/1pJvODRcTTnCvAosN0vTVtsCxD4bPEeOh/view?usp=sharing Call me up anytime you need some pixel art! 😄 So yeah. I think Web assembly support is the only thing Ebiten has over prototype. :)

**Comment by eboatwright** [comment]
Call me up anytime you need some pixel art! :smile:

**Comment by eboatwright** [comment]
Also, I forgot to tell you. The first frame, is actually and idle frame, and the rest are running. 🤦

**Comment by gonutz** [comment]
Thank you very much, I have checked this out and made a little run cycle scaled up. This is great. I will let you know in these comments when I release the video :-)

**Comment by eboatwright** [comment]
You're welcome! :smile:
