### ISSUE TITLE
is there any plan spread this library to arm architecture(android, linux on mobile etc.)?

### ISSUE THREAD

**Issue by MatejMagat305** [gonutz/prototype#9]

**Comment by gonutz** [comment]
Right now I do not have any plans to port this to mobile. It is possible, though. The API is minimal and Go runs on mobile operating systems. It is just that I personally do not have a need for it. I would welcome contributions from the community. I am not really an expert in this area, I have yet to write a mobile app beyond a simple hello world thingy.

If you or anybody out there wants to give it a shot, all you have to do is port the public API. I made it an explicit goal to keep the API minimal and clean so there should be no confusion as to what means what. The only concern is that the interface differs a bit. Keyboard input would probably just not work, touch input would have to be mapped to mouse input somehow. Or maybe a slightly different API would even make sense. I created this for desktop applications so the transition might be a bit rough, but it is possible.

**Comment by gonutz** [comment]
May I ask what you have in mind? What is your use-case?

**Comment by MatejMagat305** [comment]
I only asked, becouse I work in termux lot of time(also in go) and I was curious whether my favorite llibrary will spread.........

**Comment by gonutz** [comment]
I see, I do not know if it is possible to even compile Go apps from termux if that is what you would want to do. But as I said, since Go has been ported to mobile, IPhones and Androids I think, it is possible to port this library. But I am not the one to do it :-)

I am going to close this issue then, if you consider doing a port yourself, feel free to re-open it.
